name: build
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Root Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@{latest}
        with:
          use-gradlew: false
          gradle-build-module: |-
            :
          gradle-build-configuration: |-
            compileClasspath
